version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ratelimiter-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - ratelimiter-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ratelimiter-app
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDR: redis:6379
      DEFAULT_RATE_LIMIT_IP: 5
      DEFAULT_BLOCK_DURATION_SECONDS: 300
      # Exemplo de token customizado:
      # API_KEY_abc123: "100,60"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - ratelimiter-net

volumes:
  redis_data:
    driver: local

networks:
  ratelimiter-net:
    driver: bridge
